services:
  model-svc:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - datasets:/app/datasets
      - runs:/app/runs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  datasets:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/datasets"
  runs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/runs"